swagger: "2.0"
info:
  version: "1.0.0"
  title: API Gateway for Your Project
  description: This API Gateway routes requests to your backend services.
  contact: {}
host: YOUR_GATEWAY_DOMAIN_NAME
basePath: /
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/register:
    options:
      summary: CORS support for register endpoint
      operationId: corsRegister
      responses:
        "204":
          description: No Content
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/auth/register"
      x-google-extensions:
        cors:
          allowOrigins: ["http://localhost:3000"]
          allowMethods: ["POST", "OPTIONS"]
          allowHeaders: ["Content-Type", "Authorization"]
          maxAge: 3600
    post:
      summary: Register a new user
      description: Endpoint to register a new user
      operationId: registerUser
      produces:
        - application/json
      responses:
        "201":
          description: User registered successfully
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/auth/register"

  /auth/login:
    options:
      summary: CORS support for login endpoint
      operationId: corsLogin
      responses:
        "204":
          description: No Content
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/auth/login"
      x-google-extensions:
        cors:
          allowOrigins: ["http://localhost:3000"]
          allowMethods: ["POST", "OPTIONS"]
          allowHeaders: ["Content-Type", "Authorization"]
          maxAge: 3600
    post:
      summary: Login a user
      description: Endpoint to login a user
      operationId: loginUser
      produces:
        - application/json
      responses:
        "200":
          description: Successful login
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/auth/login"

  /products:
    options:
      summary: CORS support for products endpoint
      operationId: corsProducts
      responses:
        "204":
          description: No Content
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/products"
      x-google-extensions:
        cors:
          allowOrigins: ["http://localhost:3000"]
          allowMethods: ["POST", "OPTIONS", "GET"]
          allowHeaders: ["Content-Type", "Authorization"]
          maxAge: 3600
    post:
      summary: Create a product
      description: Endpoint to create a product (Admin only)
      operationId: createProduct
      produces:
        - application/json
      responses:
        "201":
          description: Product created successfully
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/products"
    get:
      summary: Get products
      description: Retrieve all available products
      operationId: getProducts
      produces:
        - application/json
      responses:
        "200":
          description: List of all products
      x-google-backend:
        address: "https://ok2-183873252446.asia-south1.run.app/products"

tags: []
